export const SET_APP_THEME = 'SET_APP_THEME';
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';


export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';


export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';


export const BARCODE_LOADING = 'BARCODE_LOADING';
export const BARCODE_SUCCESS = 'BARCODE_SUCCESS';
export const BARCODE_FAILED = 'BARCODE_FAILED';

export const BARCODE_IMAGE_UPLOAD_LOADING = 'BARCODE_IMAGE_UPLOAD_LOADING';
export const BARCODE_IMAGE_UPLOAD_SUCCESS = 'BARCODE_IMAGE_UPLOAD_SUCCESS';
export const BARCODE_IMAGE_UPLOAD_FAILED = 'BARCODE_IMAGE_UPLOAD_FAILED';





export const BARCODE_DETAILS_LOADING = 'BARCODE_DETAILS_LOADING';
export const BARCODE_DETAILS_SUCCESS = 'BARCODE_DETAILS_SUCCESS';
export const BARCODE_DETAILS_FAILED = 'BARCODE_DETAILS_FAILED';

export const ADD_VOUCHER_LOADING = "ADD_VOUCHER_LOADING";
export const ADD_VOUCHER_SUCCESS = "ADD_VOUCHER_SUCCESS";
export const ADD_VOUCHER_FAILED = "ADD_VOUCHER_FAILED";


export const ALL_VOUCHERS_LOADING = "ALL_VOUCHERS_LOADING";
export const ALL_VOUCHERS_SUCCESS = "ALL_VOUCHERS_SUCCESS";
export const ALL_VOUCHERS_FAILED = "ALL_VOUCHERS_FAILED";

//wallet withdraw
export const WALLET_LOADING = "WALLET_LOADING";
export const WALLET_SUCCESS = "WALLET_SUCCESS";
export const WALLET_FAILED = "WALLET_FAILED";

//wallet Balance
export const GET_BALANCE_LOADING = "GET_BALANCE_LOADING";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAILED = "GET_BALANCE_FAILED";

//wallet history
export const WALLET_HISTORY_LOADING = "WALLET_HISTORY_LOADING";
export const WALLET_HISTORY_SUCCESS = "WALLET_HISTORY_SUCCESS";
export const WALLET_HISTORY_FAILED = "WALLET_HISTORY_FAILED";


//FAQ 
export const FAQ_LOADING = "FAQ_LOADING";
export const FAQ_SUCCESS = "FAQ_SUCCESS";
export const FAQ_FAILED = "FAQ_FAILED";


//Question 
export const QUESTION_LOADING = "QUESTION_LOADING";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAILED = "QUESTION_FAILED";


//E Learning 
export const GET_COURSES_LOADING = "GET_COURSES_LOADING";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILED = "GET_COURSES_FAILED";


//E Learning add  Favorite
export const ADD_FAVORITE_LOADING = "ADD_FAVORITE_LOADING";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILED = "ADD_FAVORITE_FAILED";


//E Learning add  Favorite
export const GET_FAVORITE_LOADING = "GET_FAVORITE_LOADING";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAILED = "GET_FAVORITE_FAILED";


//E Learning add  Finished
export const GET_FINISHED_LOADING = "GET_FINISHED_LOADING";
export const GET_FINISHED_SUCCESS = "GET_FINISHED_SUCCESS";
export const GET_FINISHED_FAILED = "GET_FINISHED_FAILED";



// Stocks 
export const GET_STOCK_LOADING = "GET_STOCK_LOADING";
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_STOCK_FAILED = "GET_STOCK_FAILED";


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const PUSH_INTO_CART = "PUSH_INTO_CART";
export const RESET_CART_ARRAY = "RESET_CART_ARRAY";


// Stocks  ORDER
export const STOCK_ORDER_LOADING = "STOCK_ORDER_LOADING";
export const STOCK_ORDER_SUCCESS = "STOCK_ORDER_SUCCESS";
export const STOCK_ORDER_FAILED = "STOCK_ORDER_FAILED";




//E Stocks 
export const GET_SALE_LOADING = "GET_SALE_LOADING";
export const GET_SALE_SUCCESS = "GET_SALE_SUCCESS";
export const GET_SALE_FAILED = "GET_SALE_FAILED";


// Training 
export const GET_TRAINING_LIST_LOADING = "GET_TRAINING_LIST_LOADING";
export const GET_TRAINING_LIST_SUCCESS = "GET_TRAINING_LIST_SUCCESS";
export const GET_TRAINING_LIST_FAILED = "GET_TRAINING_LIST_FAILED";



// Training Start
export const START_TRAINING_LOADING = "START_TRAINING_LOADING";
export const START_TRAINING_SUCCESS = "START_TRAINING_SUCCESS";
export const START_TRAINING_FAILED = "START_TRAINING_FAILED";



// Training End
export const END_TRAINING_LOADING = "END_TRAINING_LOADING";
export const END_TRAINING_SUCCESS = "END_TRAINING_SUCCESS";
export const END_TRAINING_FAILED = "END_TRAINING_FAILED";

// Training 
export const GET_TRAINING_HISTORY_LOADING = "GET_TRAINING_HISTORY_LOADING";
export const GET_TRAINING_HISTORY_SUCCESS = "GET_TRAINING_HISTORY_SUCCESS";
export const GET_TRAINING_HISTORY_FAILED = "GET_TRAINING_HISTORY_FAILED";



//MRP 
export const GET_MRP_LOADING = "GET_MRP_LOADING";
export const GET_MRP_SUCCESS = "GET_MRP_SUCCESS";
export const GET_MRP_FAILED = "GET_MRP_FAILED";


//MRP Product
export const GET_MRP_PRODUCT_LOADING = "GET_MRP_PRODUCT_LOADING";
export const GET_MRP_PRODUCT_SUCCESS = "GET_MRP_PRODUCT_SUCCESS";
export const GET_MRP_PRODUCT_FAILED = "GET_MRP_PRODUCT_FAILED";



//Get display
export const GET_DISPLAY_LOADING = "GET_DISPLAY_LOADING";
export const GET_DISPLAY_SUCCESS = "GET_DISPLAY_SUCCESS";
export const GET_DISPLAY_FAILED = "GET_DISPLAY_FAILED";


//Get display Brand list
export const GET_DISPLAY_BRANDLIST_LOADING = "GET_DISPLAY_BRANDLIST_LOADING";
export const GET_DISPLAY_BRANDLIST_SUCCESS = "GET_DISPLAY_BRANDLIST_SUCCESS";
export const GET_DISPLAY_BRANDLIST_FAILED = "GET_DISPLAY_BRANDLIST_FAILED";


//Get display COMPETITORS list
export const GET_DISPLAY_COMPETITORS_LOADING = "GET_DISPLAY_COMPETITORS_LOADING";
export const GET_DISPLAY_COMPETITORS_SUCCESS = "GET_DISPLAY_COMPETITORS_SUCCESS";
export const GET_DISPLAY_COMPETITORS_FAILED = "GET_DISPLAY_COMPETITORS_FAILED";


//Get Shops
export const GET_SHOPS_LOADING = "GET_SHOPS_LOADING";
export const GET_SHOPS_SUCCESS = "GET_SHOPS_SUCCESS";
export const GET_SHOPS_FAILED = "GET_SHOPS_FAILED";



//Get Display gallery
export const GET_GALLERY_LOADING = "GET_GALLERY_LOADING";
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAILED = "GET_GALLERY_FAILED";